import type { Product } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'kbd-001',
    slug: 'dactyl-manuball-pro',
    name: 'Dactyl Manuball Pro',
    subtitle: 'Sculpted split ergonomic with integrated trackball',
    description: 'A handwired sculpted split keyboard with integrated trackball. Built for the obsessive.',
    longDescription: `The Dactyl Manuball Pro is RABID's flagship split keyboard — a handwired, fully sculpted ergonomic board with an integrated trackball module. Each unit is printed in-house, wired by hand, and flashed with QMK firmware.

The curved keywells conform to the natural arc of your fingers, eliminating the strain of flat board typing over long sessions. The integrated Manu-Ball cup holds a 34mm trackball operable by the thumb of either hand. You never leave the home row.

Every build is unique. You choose your switches, your case color, your keycap profile. RABID does the rest.`,
    category: 'keyboard',
    basePrice: 32000,
    images: ['/images/products/dactyl-manuball-1.jpg'],
    modelPath: '/assets/models/keyboard_model.json',
    tags: [
      { id: 't1', label: '76 Keys', value: '76-keys', category: 'size' },
      { id: 't2', label: 'Split', value: 'split', category: 'layout' },
      { id: 't3', label: 'Trackball', value: 'trackball', category: 'custom' },
      { id: 't4', label: 'Wireless', value: 'wireless', category: 'connectivity' },
      { id: 't5', label: 'QMK', value: 'qmk', category: 'custom' },
    ],
    variants: [
      {
        id: 'v-case-color',
        name: 'Case Color',
        type: 'color',
        required: true,
        options: [
          { id: 'ghost',  label: 'Ghost',  value: 'ghost',  priceModifier: 0,    hexColor: '#e0ddd8', available: true },
          { id: 'onyx',   label: 'Onyx',   value: 'onyx',   priceModifier: 0,    hexColor: '#1c1c1c', available: true },
          { id: 'bone',   label: 'Bone',   value: 'bone',   priceModifier: 0,    hexColor: '#f0ebe0', available: true },
          { id: 'chrome', label: 'Chrome', value: 'chrome', priceModifier: 2000, hexColor: '#c8d0d8', available: true },
          { id: 'void',   label: 'Void',   value: 'void',   priceModifier: 0,    hexColor: '#0a0a0a', available: true },
          { id: 'custom', label: 'Custom (pick below)', value: 'custom', priceModifier: 500, hexColor: '#888888', available: true },
        ],
      },
      {
        id: 'v-switch',
        name: 'Switches',
        type: 'switch',
        required: true,
        options: [
          { id: 'gateron-yellow', label: 'Gateron Yellow (Linear, 35g)', value: 'gateron-yellow', priceModifier: 0, available: true },
          { id: 'gateron-red',    label: 'Gateron Red (Linear, 45g)',    value: 'gateron-red',    priceModifier: 0, available: true },
          { id: 'holy-pandas',    label: 'Holy Pandas (Tactile, 67g)',   value: 'holy-pandas',    priceModifier: 4000, available: true },
          { id: 'boba-u4t',       label: 'Boba U4T (Tactile, 62g)',      value: 'boba-u4t',       priceModifier: 2500, available: true },
          { id: 'alpaca-v2',      label: 'Alpaca V2 (Linear, 62g)',      value: 'alpaca-v2',      priceModifier: 3500, available: true },
          { id: 'no-switch',      label: 'No switches (barebone)',       value: 'no-switch',      priceModifier: -3000, available: true },
        ],
      },
      {
        id: 'v-keycaps',
        name: 'Keycaps',
        type: 'keycap',
        required: false,
        options: [
          { id: 'kc-none',    label: 'No keycaps',           value: 'kc-none',    priceModifier: -2000, available: true },
          { id: 'kc-dsa',     label: 'DSA Blanks (PBT)',     value: 'kc-dsa',     priceModifier: 0,     available: true },
          { id: 'kc-sa',      label: 'SA Profile (PBT)',      value: 'kc-sa',      priceModifier: 1500,  available: true },
          { id: 'kc-cherry',  label: 'Cherry Profile (PBT)', value: 'kc-cherry',  priceModifier: 1200,  available: true },
          { id: 'kc-mt3',     label: 'MT3 Profile (PBT)',    value: 'kc-mt3',     priceModifier: 2500,  available: true },
        ],
      },
      {
        id: 'v-mcu',
        name: 'MCU',
        type: 'addon',
        required: true,
        options: [
          { id: 'pro-micro',  label: 'Pro Micro (USB-C wired)',         value: 'pro-micro',  priceModifier: 0,    available: true },
          { id: 'nice-nano',  label: 'nice!nano v2 (Bluetooth 5.0)',   value: 'nice-nano',  priceModifier: 3600, available: true },
          { id: 'rp2040',     label: 'RP2040 Pro Micro (USB-C fast)',   value: 'rp2040',     priceModifier: 400,  available: true },
        ],
      },
      {
        id: 'v-firmware',
        name: 'Firmware',
        type: 'addon',
        required: false,
        options: [
          { id: 'qmk',  label: 'QMK (default, wired)',    value: 'qmk',  priceModifier: 0,   available: true },
          { id: 'zmk',  label: 'ZMK (wireless/BT)',       value: 'zmk',  priceModifier: 500, available: true },
          { id: 'via',  label: 'VIA-compatible QMK',      value: 'via',  priceModifier: 0,   available: true },
        ],
      },
      {
        id: 'v-cover',
        name: 'Case Cover',
        type: 'addon',
        required: false,
        options: [
          { id: 'cover-none',  label: 'No cover',            value: 'cover-none',  priceModifier: 0,    available: true },
          { id: 'cover-tpu',   label: 'TPU Wrist Rest',      value: 'cover-tpu',   priceModifier: 1800, available: true },
          { id: 'cover-wood',  label: 'Walnut Palm Rest',    value: 'cover-wood',  priceModifier: 3500, available: true },
        ],
      },
      {
        id: 'v-tenting',
        name: 'Tenting Kit',
        type: 'addon',
        required: false,
        options: [
          { id: 'tent-none',  label: 'No tenting',          value: 'tent-none',  priceModifier: 0,    available: true },
          { id: 'tent-5deg',  label: '5° tenting legs',     value: 'tent-5deg',  priceModifier: 800,  available: true },
          { id: 'tent-15deg', label: '15° tenting legs',    value: 'tent-15deg', priceModifier: 800,  available: true },
          { id: 'tent-mag',   label: 'Magnetic adjustable', value: 'tent-mag',   priceModifier: 2200, available: true },
        ],
      },
      {
        id: 'v-display',
        name: 'Display / OLED',
        type: 'addon',
        required: false,
        options: [
          { id: 'disp-none',  label: 'No display',          value: 'disp-none',  priceModifier: 0,   available: true },
          { id: 'disp-oled',  label: '0.91" OLED (WPM/layer)', value: 'disp-oled', priceModifier: 600, available: true },
          { id: 'disp-nice',  label: 'nice!view e-ink',     value: 'disp-nice',  priceModifier: 2400, available: true },
        ],
      },
    ],
    specs: {
      'Layout': 'Dactyl Manuball (76 key split)',
      'Case Material': 'PLA+ / PETG (3D printed)',
      'PCB': 'Handwired with Pro Micro / nice!nano',
      'Switch Support': 'MX compatible (5-pin/3-pin)',
      'Trackball': '34mm optical (PMW3360 sensor)',
      'Connectivity': 'USB-C / Bluetooth 5.0 (with nice!nano)',
      'Firmware': 'QMK / ZMK',
      'Weight': '~480g (pair)',
      'Dimensions': '~300 × 140 × 60mm (per half)',
    },
    inStock: true,
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'kbd-002',
    slug: 'low-profile-corne',
    name: 'Corne LP',
    subtitle: 'Low-profile 42-key split with Choc switches',
    description: 'Ultra-thin column-staggered split. Travels with you. Punishes nothing.',
    longDescription: `The Corne LP (low-profile) is RABID's most portable offering. A 42-key column-staggered split built around Kailh Choc switches. At under 14mm total height, it disappears into any bag.

Pre-built with hotswap sockets and shipped with a matched set of Choc browns. Firmware pre-loaded with a sensible default keymap. You remap everything via VIA — no compile required.`,
    category: 'keyboard',
    basePrice: 18500,
    images: ['/images/products/corne-lp-1.jpg'],
    modelPath: '/assets/models/corne_model.json',
    tags: [
      { id: 't6', label: '42 Keys', value: '42-keys', category: 'size' },
      { id: 't7', label: 'Split', value: 'split', category: 'layout' },
      { id: 't8', label: 'Hotswap', value: 'hotswap', category: 'custom' },
      { id: 't9', label: 'Low Profile', value: 'low-profile', category: 'custom' },
      { id: 't10', label: 'VIA', value: 'via', category: 'custom' },
    ],
    variants: [
      {
        id: 'v-case-color',
        name: 'Case Color',
        type: 'color',
        required: true,
        options: [
          { id: 'black',  label: 'Matte Black',  value: 'black',  priceModifier: 0,   hexColor: '#111111', available: true },
          { id: 'white',  label: 'Chalk White',  value: 'white',  priceModifier: 0,   hexColor: '#f0f0f0', available: true },
          { id: 'grey',   label: 'Slate Grey',   value: 'grey',   priceModifier: 0,   hexColor: '#888888', available: true },
          { id: 'custom', label: 'Custom (pick below)', value: 'custom', priceModifier: 500, hexColor: '#cccccc', available: true },
        ],
      },
      {
        id: 'v-switch',
        name: 'Switches',
        type: 'switch',
        required: true,
        options: [
          { id: 'choc-brown', label: 'Choc Brown (Tactile, 60g)', value: 'choc-brown', priceModifier: 0,    available: true },
          { id: 'choc-red',   label: 'Choc Red (Linear, 45g)',   value: 'choc-red',   priceModifier: 0,    available: true },
          { id: 'choc-white', label: 'Choc White (Clicky, 45g)', value: 'choc-white', priceModifier: 0,    available: true },
          { id: 'choc-ks27',  label: 'KS-27 Pink (Linear, 45g)', value: 'choc-ks27', priceModifier: 800,  available: true },
          { id: 'no-switch',  label: 'No switches (barebone)',   value: 'no-switch',  priceModifier: -1500, available: true },
        ],
      },
      {
        id: 'v-keycaps',
        name: 'Keycaps',
        type: 'keycap',
        required: false,
        options: [
          { id: 'kc-none',      label: 'No keycaps',               value: 'kc-none',    priceModifier: -1500, available: true },
          { id: 'kc-choc-lp',   label: 'Choc LP Blanks (PBT)',    value: 'kc-choc-lp', priceModifier: 0,     available: true },
          { id: 'kc-mbk',       label: 'MBK Legends (PBT)',        value: 'kc-mbk',     priceModifier: 1200,  available: true },
          { id: 'kc-ldsa',      label: 'LDSA Profile (PBT)',       value: 'kc-ldsa',    priceModifier: 1800,  available: true },
        ],
      },
      {
        id: 'v-mcu',
        name: 'MCU',
        type: 'addon',
        required: true,
        options: [
          { id: 'pro-micro', label: 'Pro Micro (wired)',          value: 'pro-micro', priceModifier: 0,    available: true },
          { id: 'nice-nano', label: 'nice!nano v2 (wireless)',    value: 'nice-nano', priceModifier: 3600, available: true },
        ],
      },
      {
        id: 'v-display',
        name: 'Display',
        type: 'addon',
        required: false,
        options: [
          { id: 'disp-none', label: 'No display',             value: 'disp-none', priceModifier: 0,   available: true },
          { id: 'disp-oled', label: '0.91" OLED',             value: 'disp-oled', priceModifier: 600, available: true },
          { id: 'disp-nice', label: 'nice!view e-ink',        value: 'disp-nice', priceModifier: 2400, available: true },
        ],
      },
      {
        id: 'v-tenting',
        name: 'Tenting',
        type: 'addon',
        required: false,
        options: [
          { id: 'tent-none',  label: 'No tenting',      value: 'tent-none',  priceModifier: 0,   available: true },
          { id: 'tent-5deg',  label: '5° tenting legs', value: 'tent-5deg',  priceModifier: 800, available: true },
        ],
      },
    ],
    specs: {
      'Layout': 'Corne (42 key split)',
      'Switch': 'Kailh Choc v1 (hotswap)',
      'PCB': 'Custom RABID LP PCB',
      'Connectivity': 'USB-C',
      'Firmware': 'QMK / VIA',
      'Height': '14mm (deck to desk)',
      'Weight': '~210g (pair)',
    },
    inStock: true,
    featured: true,
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'kbd-003',
    slug: 'planck-rabid',
    name: 'Planck RABID',
    subtitle: '48-key ortholinear powerhouse',
    description: 'No compromise ortholinear. Every key within reach.',
    longDescription: `The Planck RABID is a 4×12 ortholinear keyboard — 48 keys in a perfect grid. No stagger, no compromise. Layers handle everything you need.

Shipped fully assembled with your switch choice. CNC-aluminium case. USB-C only. QMK pre-flashed.`,
    category: 'keyboard',
    basePrice: 15000,
    images: ['/images/products/planck-1.jpg'],
    tags: [
      { id: 't11', label: '48 Keys', value: '48-keys', category: 'size' },
      { id: 't12', label: 'Ortholinear', value: 'ortholinear', category: 'layout' },
      { id: 't13', label: 'Full Size', value: 'full', category: 'size' },
      { id: 't14', label: 'Aluminium', value: 'aluminium', category: 'custom' },
    ],
    variants: [
      {
        id: 'v-case-color',
        name: 'Case Finish',
        type: 'color',
        required: true,
        options: [
          { id: 'ano-black', label: 'Anodized Black', value: 'ano-black', priceModifier: 0,     hexColor: '#111', available: true },
          { id: 'natural',   label: 'Natural Aluminium', value: 'natural', priceModifier: 0,    hexColor: '#b8b8b8', available: true },
          { id: 'raw',       label: 'Raw (Unfinished)', value: 'raw',     priceModifier: -2000, hexColor: '#d4d4d4', available: true },
        ],
      },
      {
        id: 'v-switch',
        name: 'Switch',
        type: 'switch',
        required: true,
        options: [
          { id: 'g-pro-yellow', label: 'Gateron G Pro Yellow', value: 'g-pro-yellow', priceModifier: 0,    available: true },
          { id: 'alpaca-v2',    label: 'Alpaca V2 (Linear)',   value: 'alpaca-v2',    priceModifier: 3500, available: true },
        ],
      },
      {
        id: 'v-keycaps',
        name: 'Keycaps',
        type: 'keycap',
        required: false,
        options: [
          { id: 'kc-none',   label: 'No keycaps',        value: 'kc-none',   priceModifier: -1000, available: true },
          { id: 'kc-dsa',    label: 'DSA Blanks (PBT)',  value: 'kc-dsa',    priceModifier: 0,     available: true },
          { id: 'kc-cherry', label: 'Cherry Profile',    value: 'kc-cherry', priceModifier: 1200,  available: true },
        ],
      },
    ],
    specs: {
      'Layout': 'Planck (48 key ortholinear)',
      'Case': 'CNC 6063 Aluminium',
      'Mount': 'Top mount',
      'Switch': 'MX 5-pin hotswap',
      'Firmware': 'QMK',
      'Weight': '~620g',
    },
    inStock: true,
    featured: false,
    createdAt: '2024-02-01T00:00:00Z',
  },
  {
    id: 'kbd-004',
    slug: 'kyria-rabid-edition',
    name: 'Kyria RE',
    subtitle: 'Thumb-cluster split with 5-column stagger',
    description: 'Aggressive column stagger. Up to 6 thumb keys. The layout that converts.',
    longDescription: `The Kyria RABID Edition is a thoroughly opinionated split keyboard. Heavy column stagger mirrors the actual offset of your fingers. Six thumb keys per side. Hotswap by default.`,
    category: 'keyboard',
    basePrice: 21000,
    images: ['/images/products/kyria-1.jpg'],
    tags: [
      { id: 't19', label: '64 Keys', value: '64-keys', category: 'size' },
      { id: 't20', label: 'Split', value: 'split', category: 'layout' },
      { id: 't21', label: 'Hotswap', value: 'hotswap', category: 'custom' },
      { id: 't22', label: 'Medium', value: 'medium', category: 'size' },
    ],
    variants: [
      {
        id: 'v-case-color',
        name: 'Case Color',
        type: 'color',
        required: true,
        options: [
          { id: 'matte-black', label: 'Matte Black',   value: 'matte-black', priceModifier: 0,   hexColor: '#111', available: true },
          { id: 'frosted',     label: 'Frosted Clear', value: 'frosted',     priceModifier: 500, hexColor: '#e8e8e8', available: true },
        ],
      },
      {
        id: 'v-switch',
        name: 'Switch',
        type: 'switch',
        required: true,
        options: [
          { id: 'gat-yellow', label: 'Gateron Yellow', value: 'gat-yellow', priceModifier: 0,    available: true },
          { id: 'boba-u4t',   label: 'Boba U4T',       value: 'boba-u4t',   priceModifier: 2500, available: true },
        ],
      },
    ],
    specs: {
      'Layout': 'Kyria (64 key split)',
      'Stagger': '5-column aggressive',
      'Thumb Cluster': '6 keys per half',
      'Firmware': 'QMK / ZMK',
    },
    inStock: false,
    featured: false,
    createdAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'acc-001',
    slug: 'nice-nano-v2',
    name: 'nice!nano v2',
    subtitle: 'Pro Micro compatible wireless MCU',
    description: 'Bluetooth 5.0 MCU. Drop-in Pro Micro replacement. Powers ZMK.',
    longDescription: 'The nice!nano v2 is the definitive wireless MCU for split keyboards. nRF52840-based, Pro Micro pin-compatible, designed for ZMK firmware.',
    category: 'accessory',
    basePrice: 1800,
    images: ['/images/products/nice-nano-1.jpg'],
    tags: [
      { id: 't15', label: 'MCU', value: 'mcu', category: 'custom' },
      { id: 't16', label: 'Wireless', value: 'wireless', category: 'connectivity' },
    ],
    variants: [],
    specs: { 'MCU': 'nRF52840', 'Bluetooth': '5.0', 'Connector': 'USB-C' },
    inStock: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'acc-002',
    slug: 'premium-soldering-kit',
    name: 'Precision Soldering Kit',
    subtitle: 'Everything you need. Nothing you don\'t.',
    description: 'Curated soldering kit for keyboard builds.',
    longDescription: 'RABID\'s curated soldering kit includes 63/37 flux-core solder (0.6mm), tip cleaner, brass wool, reverse-action tweezers, and a silicone mat.',
    category: 'accessory',
    basePrice: 2200,
    images: ['/images/products/solder-kit-1.jpg'],
    tags: [
      { id: 't17', label: 'Soldering', value: 'soldering', category: 'custom' },
      { id: 't18', label: 'Tools', value: 'tools', category: 'custom' },
    ],
    variants: [],
    specs: { 'Solder': '63/37 Flux-core, 0.6mm', 'Weight (spool)': '100g' },
    inStock: true,
    featured: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
]

export const ALL_TAGS = Array.from(
  new Map(
    MOCK_PRODUCTS.flatMap((p) => p.tags).map((t) => [t.value, t])
  ).values()
)
